# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :CI do
      run_tests(workspace: "flickrAPI-image-search.xcworkspace",
      devices: ["iPhone 11 Pro Max"],
      scheme: "flickrAPI-image-search")
  end

  lane :CD do |values|
 
    gym(scheme: 'flickrAPI-image-search', 
    	workspace: "flickrAPI-image-search.xcworkspace", 
    	configuration: "Debug",
    	clean: true, 
    	silent: true, 
    	include_bitcode: false, 
    	export_method: 'ad-hoc',
    	xcargs: "-allowProvisioningUpdates",
    	export_options: {
                signingStyle: "automatic"
        })
 
    emails = values[:test_email] ? values[:test_email] : ['[email]'] # You can list more emails here
    groups = values[:test_email] ? nil : nil # You can define groups on the web and reference them here
 
    upload_symbols_to_crashlytics(gsp_path: "./App/GoogleService-Info.plist")
 
    end
end
